- hosts: localhost
  vars:
    source_key: "./ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  tasks:
    - import_tasks: tasks/audio.yml
    - import_tasks: tasks/bluetooth.yml
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/zsh-setup.yml
    - import_tasks: tasks/st-setup.yml
    # - import_tasks: tasks/dwm.yml
    - import_tasks: tasks/i3.yml
    - import_tasks: tasks/productivity-tools.yml
    - import_tasks: tasks/yay.yml
    - import_tasks: tasks/brave.yml
    - import_tasks: tasks/slack.yml

