- name: something
  become: true
  community.general.pacman:
    state: present
    name:
      - base-devel
      - libx11
      - libxinerama
      - libxft
      - freetype2
  tags:
    - dwm
- name: Clone dwm
  become: true
  become_user: andrei
  ansible.builtin.git:
    repo: 'https://github.com/tekdel/dwm.git'
    dest: ~/personal/dwm
  tags:
    - dwm
- name: Install dwm
  shell: cd ~/personal/dwm && make && sudo make install
  tags:
    - dwm

