- name: Install i3
  become: true
  community.general.pacman:
    update_cache: true
    state: present
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xrandr
      - autorandr
      - xterm
      - mesa
      - i3
      - i3blocks
      - ttf-jetbrains-mono-nerd
      - dmenu
  tags:
    - i3
