- name: Install i3
  become: true
  community.general.pacman:
    update_cache: true
    state: present
    name:
      - xorg-server
      - xorg-xinit
      - xterm
      - mesa
      - i3
      - i3blocks
  tags:
    - i3
