- name: Install packages
  become: true
  community.general.pacman:
    update_cache: true
    state: present
    name:
      - tmux
      - fzf
      - gimp
      - xclip
      - ripgrep
      - shutter
      - unzip
  tags:
    - install
    - productivity
