- name: Install packages
  become: true
  community.general.pacman:
    update_cache: true
    state: present
    name:
      - tmux
      - fzf
      - gimp
      - xclip
      - ripgrep
      - shutter
      - unzip
      - docker
      - docker-compose
      - dbeaver
  tags:
    - productivity
- name: Enable docker
  become: true
  shell: systemctl enable docker
  tags:
    - productivity
- name: Start docker
  become: true
  shell: systemctl start docker
  tags:
    - productivity
- name: Add user to docker group
  become: true
  shell: usermod -aG docker andrei
  tags:
    - productivity
