- name: Install packages
  become: true
  community.general.pacman:
    update_cache: true
    state: present
    name:
      - tmux
      - fzf
      - gimp
      - xclip
      - ripgrep
      - maim # screenshots
      - unzip
      - docker
      - docker-compose
      - dbeaver
      - alsa-utils
      - bolt # thunderbolt
      - fwupd # thunderbolt
  tags:
    - productivity

- name: Install yay
  import_tasks: tasks/yay.yml
  tags:
    - productivity

- name: Install Zoom 1Password
  shell: yay -S zoom 1password --noconfirm
  tags:
    - productivity

- name: Enable docker
  become: true
  shell: systemctl enable docker
  tags:
    - productivity

- name: Start docker
  become: true
  shell: systemctl start docker
  tags:
    - productivity

- name: Add user to docker group
  become: true
  shell: usermod -aG docker andrei
  tags:
    - productivity

- name: Create pictures folder
  shell: mkdir -p ~/pictures/screenshots && mkdir -p ~/pictures/screencasts
  tags:
    - productivity
